### ISSUE TITLE
mkdir(): Permission denied

### ISSUE THREAD

**Issue by andregeges** [heybigname/backup-manager#51]
I got this setup for storage and when i run 

db:backup from terminal

or

$manager = App::make('BigName\BackupManager\Manager');
$manager->makeBackup()->run('mysql', 'local', 'backup.sql', 'gzip');

from routes app

i got this error mkdir(): Permission denied

'local' => [
        'type' => 'Local',
        'root' => '/Application/MAMP/htdocs/laravel/public/uploads/',
    ],

**Comment by ShawnMcCool** [comment]
I'm sorry, I can't think of a way to directly troubleshoot this with you. However, in an upcoming version our goal is to give better error messages when filesystem permissions must be changed.

Change your user account to the user that your php process runs as. Then, go to the folder 'root' and try to make folders and files. If you can't then you need to update your local filesystem permissions so that you can.
